profile:
  parameters:
    snowflake:
      account: ascendpartner
      user: nandan_inception_test
      database: ottos_expeditions
      schema: ottos_expeditions
      warehouse: nandan_inception_test
      role: nandan_inception_test

  defaults:
    - kind: Flow
      name:
        regex: .*
      spec:
        data_plane:
          connection_name: snowflake_data_plane
