profile:
  parameters:
    snowflake:
      account: ascendpartner
      user: nandan_inception_test
      database: nandan_inception_test
      schema: nandan_inception_test
      warehouse: nandan_inception_test
      role: nandan_inception_test

  defaults:
    - kind: Flow
      name:
        regex: .*
      spec:
        data_plane:
          connection_name: snowflake_data_plane
