profile:
  parameters:
    snowflake:
      account: PIAGRRP-ASCENDPARTNER
      user: SEAN_DEV_ENV_DEV
      database: SEAN_DEV
      schema: OTTOS_EXPEDITIONS
      warehouse: SEAN_DEV
      role: SEAN_DEV_ENV_DEV

  defaults:
    - kind: Flow
      name:
        regex: .*
      spec:
        data_plane:
          connection_name: snowflake_data_plane
