profile:
  parameters:
    snowflake:
      account: ascendpartner
      user: KYLE_INSTANCE
      database: KYLE_OSBORNE_DEMO
      schema: INCEPTION_LOCAL_DEV_OTTO_EXPEDITIONS
      warehouse: TEST
      role: KYLE_LOCAL_DEV

  defaults:
    - kind: Flow
      name:
        regex: .*
      spec:
        data_plane:
          connection_name: snowflake_data_plane
