profile:
  parameters:
    snowflake:
      account: ascendpartner
      user: ASCEND_CODY_PROD
      database: ASCEND_CODY_PROD
      schema: ASCEND_CODY_PROD
      warehouse: ASCEND_CODY_PROD
      role: ASCEND_CODY_PROD

  defaults:
    - kind: Flow
      name:
        regex: .*
      spec:
        data_plane:
          connection_name: snowflake_data_plane
