profile:
  parameters:
    snowflake:
      account: <your-snowflake-account>
      user: ASCEND_CODY_STAGING
      database: ASCEND_CODY_STAGING
      schema: ASCEND_CODY_STAGING
      warehouse: ASCEND_CODY_STAGING
      role: ASCEND_CODY_STAGING

  defaults:
    - kind: Flow
      name:
        regex: .*
      spec:
        data_plane:
          connection_name: snowflake_data_plane
