automation:
  enabled: true
  name: test
  triggers:
    sensors:
      - type: timer
        config:
          schedule:
            cron: 45 0 * * 0
  actions:
    - type: run_flow
      config:
        flow: elt
