automation:
  enabled: true
  name: test
  triggers:
    events:
      - sql_filter: json_extract_string(event, '$.data.flow') = 'elt'
        types:
          - FlowRunSuccess
    sensors:
      - type: timer
        config:
          schedule:
            cron: 45 0 * * 0
  actions:
    - type: run_flow
      config:
        flow: elt
    - type: run_flow
