profile:
  parameters:
    gcp:
      project_id: ascend-io-cody
    bigquery:
      dataset: OE_LOCAL_DEV
      location: US

  defaults:
    - kind: Flow
      name:
        regex: .*
      spec:
        data_plane:
          connection_name: bigquery_data_plane
