profile:
  parameters:
    gcp:
      project_id: ayour-gcp-project>
    bigquery:
      dataset: ASCEND_COMMUNITY_OTTOS_EXPEDITIONS_STAGING_CICD
      location: US

  defaults:
    - kind: Flow
      name:
        regex: .*
      spec:
        data_plane:
          connection_name: bigquery_data_plane
