profile:
  parameters:
    databricks:
      workspace_url: "https://adb-3886704123539288.8.azuredatabricks.net/"
      cluster_id: 0315-003230-p3sjg0zc
      client_id: ff29eec7-aba2-4132-b8c5-b23adbc42a7e
      http_path: sql/protocolv1/o/3886704123539288/0315-003230-p3sjg0zc
      catalog: ascend_dbx
      schema: dev

  defaults:
    - kind: Flow
      name:
        regex: .*
      spec:
        data_plane:
          connection_name: databricks_data_plane
