profile:
  parameters:
    databricks:
      workspace_url: "https://adb-1449496082990571.11.azuredatabricks.net/"
      cluster_id: 0316-223040-ecq4yzcn
      client_id: 76c19ed6-c550-4284-968b-c1350cb96885
      http_path: sql/protocolv1/o/1449496082990571/0316-223040-ecq4yzcn
      catalog: ascend_data_plane_dev_sean
      schema: default

  defaults:
    - kind: Flow
      name:
        regex: .*
      spec:
        data_plane:
          connection_name: databricks_data_plane
