profile:
  parameters:
    databricks:
      workspace_url: <your-databricks-workspace-url>
      client_id: <your-databricks-client-id>
      cluster_id: <your-databricks-cluster-id>
      http_path: <your-databricks-http-path>
      catalog: dbx_catalog
      schema: prod

  defaults:
    - kind: Flow
      name:
        regex: .*
      spec:
        data_plane:
          connection_name: databricks_data_plane
