automation:
  enabled: true
  name: nightly
  triggers:
    sensors:
      - type: timer
        config:
          schedule:
            cron: 0 4 * * *
  actions:
    - type: run_flow
      config:
        flow: elt
