automation:
  enabled: true
  name: downstreams-databricks
  triggers:
    events:
      - sql_filter: json_extract_string(event, '$.data.flow') = 'transform-databricks'
        types:
          - FlowRunSuccess
  actions:
    - type: run_flow
      name: run-metrics-databricks
      config:
        flow: metrics-databricks
    - type: run_flow
      name: run-pyspark-databricks
      config:
        flow: pyspark-databricks
