automation:
  enabled: true
  name: downstreams-bigquery
  triggers:
    events:
      - sql_filter: json_extract_string(event, '$.data.flow') = 'transform-bigquery'
        types:
          - FlowRunSuccess
  actions:
    - type: run_flow
      name: run-metrics-bigquery
      config:
        flow: metrics-bigquery
