automation:
  enabled: true
  name: extract-load-snowflake
  triggers:
    sensors:
      - type: timer
        name: cron-timer
        config:
          schedule:
            cron: 0 * * * *
  actions:
    - type: run_flow
      name: run-extract-load-snowflake
      config:
        flow: extract-load-snowflake
