automation:
  enabled: true
  name: transform-databricks
  triggers:
    events:
      - sql_filter: json_extract_string(event, '$.data.flow') = 'extract-load-databricks'
        types:
          - FlowRunSuccess
  actions:
    - type: run_flow
      name: run-transform-databricks
      config:
        flow: transform-databricks
