automation:
  enabled: true
  name: transform-snowflake
  triggers:
    events:
      - sql_filter: json_extract_string(event, '$.data.flow') = 'extract-load-snowflake'
        types:
          - FlowRunSuccess
  actions:
    - type: run_flow
      name: run-transform-snowflake
      config:
        flow: transform-snowflake
