automation:
  enabled: true
  name: transform-bigquery
  triggers:
    events:
      - sql_filter: json_extract_string(event, '$.data.flow') = 'extract-load-bigquery'
        types:
          - FlowRunSuccess
  actions:
    - type: run_flow
      name: run-transform-bigquery
      config:
        flow: transform-bigquery
