default:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'jaffle_shop.duckdb'
      threads: 24
    prod:
      type: snowflake
      account: "{{env_var('DBT_ENV_SNOWFLAKE_ACCOUNT')}}"
      user: "{{env_var('DBT_ENV_SNOWFLAKE_USER')}}"
      private_key: "{{env_var('DBT_ENV_SECRET_SNOWFLAKE_PRIVATE_KEY')}}"
      role: "{{env_var('DBT_ENV_SNOWFLAKE_ROLE')}}"
      database: "{{env_var('DBT_ENV_SNOWFLAKE_DATABASE')}}"
      warehouse: "{{env_var('DBT_ENV_SNOWFLAKE_WAREHOUSE')}}"
      schema: "{{env_var('DBT_ENV_SNOWFLAKE_SCHEMA')}}"
