profile:
  parameters:

    snowflake:
      # Snowflake account
      # e.g. account: wvwohks-syb91821
      account: PIAGRRP-ascendpartner

      # adjust the values below if needed
      warehouse: SEAN_DEV
      database: SEAN_DEV
      user: SEAN_DEV_ENV_DEV
      schema: SEAN_DEV_ENV_DEV
      role: SEAN_DEV_ENV_DEV

  defaults:
    - kind: Flow
      name:
        regex: .*
      spec:
        data_plane:
          connection_name: snowflake_data_plane
