automation:
  enabled: true
  name: extract-load
  triggers:
    sensors:
      - type: timer
        name: cron-timer
        config:
          schedule:
            cron: ${parameters.duckdb.automations.duckdb_schedule}
  actions:
    - type: run_flow
      name: run-extract-load
      config:
        flow: extract-load
