profile:
  parameters:

    snowflake:
      # Snowflake account
      # e.g. account: wvwohks-syb91821
      account: ascendpartner

      # adjust the values below if needed
      user: ASCEND_CODY_OO_DEV_V0
      database: ASCEND_CODY_OO_DEV_V0
      schema: ASCEND_CODY_OO_DEV_V0
      warehouse: ASCEND_CODY_OO_DEV_V0
      role: ASCEND_CODY_OO_DEV_V0

  defaults:
    - kind: Flow
      name:
        regex: .*
      spec:
        data_plane:
          connection_name: snowflake_data_plane
