automation:
  enabled: true
  name: extract-load
  triggers:
    sensors:
      - type: timer
        name: cron-timer
        config:
          schedule:
            cron: 'R(0-59) */4 * * *'
  actions:
    - type: run_flow
      name: run-extract-load
      config:
        flow: extract-load
