profile:
  parameters:

    warehouse:
      # like 'xxx-yyy.datawarehouse.fabric.microsoft.com'
      server: rnm2l42d4amupafhjgzdarv55q-3hrhjmkduv4ufimdwgauatkyzm.datawarehouse.fabric.microsoft.com
      # If you chose a different name for the warehouse, use that below
      name: ascend_data_plane_warehouse
      # If you chose a different schema for the warehouse, use that below
      schema: quickstart

    service_principal:
      # client_id is the same as appId in various places in Azure
      client_id: ef0a50f3-488e-47ae-ad1f-d167805a3463
      # tenant_id is sometimes tenant or directory id in Azure
      tenant_id: f3a5598b-e043-4719-80a7-49b23046bdec

    storage_account:
      name: ascendfabricquickstart
      # If you chose a different path for the storage container name, use that below
      path: "abfss://ascend-staging"

  defaults:
    - kind: Flow
      name:
        regex: .*
      spec:
        data_plane:
          connection_name: fabric_data_plane
