automation:
  name: otto-slack-success
  enabled: true
  triggers:
    events:
      - types:
            - FlowRunSuccess
  actions:
    - type: run_otto
      name: slack-success-summary
      config:
        prompt: >-
          # Instructions

          A Flow run has just completed successfully. Your objective is to gather
          pertinent information about the successful run and post a concise summary
          message to Slack to keep other users informed.

          You cannot ask for help or clarification; you must complete this task
          end-to-end on your own. Your last action must always be to post a message to Slack.

          ## Information Gathering Steps

          Follow these steps in order to gather context about the successful run:

          1. Fetch Flow metadata: Get the Flow name, run name, and environment information

          2. Get run statistics: Retrieve execution time, Components processed, and data volumes if available

          3. Check recent history: Get the last 10 runs to understand if this success follows any recent failures

          4. Identify key metrics: Look for relevant performance metrics (rows processed, files generated, etc.)

          5. Review any notable changes: Check if this run included any recent code or configuration changes

          6. Write and post Slack message: Summarize the successful run in a clear, informative message

          ## Slack Message Requirements

          Post your summary to Slack in the appropriate channel. Your message must include:

          ### Required Information:
          - Flow name and run identifier
          - Execution duration (start time to completion time)
          - Number of Components successfully executed
          - Data volumes processed (rows, files, or size if available)
          - Any notable performance metrics or highlights
          - Link to the Flow run: https://[runtime.link_url]/flows/[flow_name]/[run_name]

          ### Contextual Information (if relevant):
          - Recovery from previous failures (e.g., "First successful run after 3 consecutive failures")
          - Performance improvements or degradations compared to typical runs
          - Any warnings or non-critical issues that should be monitored

          ### Message Tone:
          - Keep it concise and positive
          - Focus on actionable insights, not just "it worked"
          - Only include details that are meaningful to stakeholders

          ## Example Slack Message Format

          :white_check_mark: PIPELINE SUCCESS: sales :white_check_mark:

          Status: Completed successfully in 4 minutes 23 seconds

          Summary:
          - All 4 Components executed successfully
          - Processed 125,847 rows across 3 tables
          - Generated sales aggregations for Q4 2024

          Performance: Execution time is 15% faster than the 7-day average (5m 8s)

          Context: This is the first successful run after 2 consecutive failures due to permission issues, which have now been resolved.

          Flow run: https://[runtime.link_url]/flows/sales/run-20241112-143022
