# justfile

# load environment variables
set dotenv-load

# variables
locallakedir:="lake"
remotelakedir:="lakev2"

# aliases
alias fmt:=format
alias install:=sync

# list justfile recipes
default:
    just --list

# python things
setup:
    @uv venv --python=3.12 --allow-existing
    just sync

sync:
    @uv sync --all-extras --upgrade

install-core:
    @uv pip install $HOME/code/ascend-io/core

build-python:
    @rm -r dist || true
    @uv build

format:
    @ruff format .

# preview
preview:
    quarto preview website

# build
build:
    quarto render website

# cloud stuff
# TODO: azcopy or Python code; or ideally Ascend
upload-az:
    @azcopy sync {{locallakedir}} "https://codyascend.blob.core.windows.net/cody-public/{{remotelakedir}}"

upload-gs:
    @gsutil -m rsync -r {{locallakedir}} gs://ascend-io-gcs-public/{{remotelakedir}}

upload:
    @echo "uploading to az..."
    just upload-az
    @echo "\n\nuploading to gs..."
    just upload-gs

# clean
clean-lake:
    @rm -rf {{locallakedir}}
    @mkdir -p {{locallakedir}}

clean:
    rm -rf website/_site
    rm -rf website/_freeze
    rm -rf website/.quarto

