name: ottos-expeditions-bigquery

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    paths:
      - "ottos-expeditions/**"
      - ".github/actions/ottos-expeditions.yaml"
      - ".github/workflows/ottos-expeditions-bigquery.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  datagen:
    # to check if the event was labelling...
    # if: ${{ github.event.label.name == 'run_datagen_on_pr' }}
    # to check if the PR has the label...
    if: contains(github.event.pull_request.labels.*.name, 'run_datagen_on_pr')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ottos-expeditions
    steps:
      # common setup
      - uses: ./.github/actions/ottos-expeditions

      # run bigquery test
      - run: just test-bigquery
