name: ottos-expeditions-datagen

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    paths:
      - "ottos-expeditions/**"
      - ".github/actions/ottos-expeditions/**"
      - ".github/workflows/ottos-expeditions-datagen.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  datagen:
    if: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'run_datagen_on_pr') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ottos-expeditions
    steps:
      # install ottos-expeditions
      - uses: ./.github/workflows/ottos-expeditions.yaml

      # run datagen
      - run: |
          . .venv/bin/activate
          ottos-expeditions datagen --days 7

      - run: just upload-gs
