name: ottos-expeditions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    paths:
      - "ottos-expeditions/**"
      - ".github/workflows/ottos-expeditions.yaml"

  # push:
  #   branches: ["main"]
  #   paths:
  #     - "ottos-expeditions/**"
  #     - ".github/workflows/ottos-expeditions.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  datagen:
    # to check if the event was labelling...
    # if: ${{ github.event.label.name == 'run_datagen_on_pr' }}
    # to check if the PR has the label...
    if: contains(github.event.pull_request.labels.*.name, 'run_datagen_on_pr')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ottos-expeditions
    steps:
      # checkout the repository
      - name: checkout
        uses: actions/checkout@v4

      # setup gcloud
      - name: 'GCP auth'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'GCP SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      # install Python and just and uv
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - uses: extractions/setup-just@v1
      - uses: astral-sh/setup-uv@v5

      # install ottos-expeditions
      - run: just install

      # run datagen
      - run: |
          . .venv/bin/activate
          ottos-expeditions datagen --days 7

      - run: just upload-gs
