name: ottos-expeditions-cicd
description: "Common CI/CD setup for Otto's Expeditions"

runs:
  using: "composite"
  steps:
    # checkout the repository
    - name: checkout
      uses: actions/checkout@v4

    # setup gcloud
    - name: 'GCP auth'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: ${{ vars.GCP_PROJECT_ID }}
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'GCP SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    # install Python and just and uv
    - uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - uses: extractions/setup-just@v1
    - uses: astral-sh/setup-uv@v5

    # install ottos-expeditions
    - run: just install

